spring:
  application:
    name: so-java-stats

  datasource:
    url: jdbc:postgresql://localhost:5432/stackoverflow
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 800000
      auto-commit: true
      leak-detection-threshold: 2400000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
